**🌟 Exercise 1 : Array Creation and Manipulation**

**Instructions**

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**🌟 Exercise 2 : Type Conversion and Array Operations**

**Instructions**

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

array([3, 2, 0, 1, 2])

In [4]:
list_data = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(list_data, dtype=int)
arr2

array([3, 2, 0, 1, 2])

**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

**Instructions**

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

**Instructions**

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:

array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [6]:
arr4 = np.random.rand(4, 5)
arr4

array([[0.22023834, 0.42949132, 0.84949938, 0.19244799, 0.24219291],
       [0.56637134, 0.57049727, 0.41415272, 0.2816387 , 0.9036918 ],
       [0.35803219, 0.7973546 , 0.99956791, 0.97311878, 0.24071406],
       [0.52228167, 0.36534688, 0.4076275 , 0.87266452, 0.49190547]])

**🌟 Exercise 5 : Indexing Arrays**

**Instructions**

Select the second row from a given 2D NumPy array.

Expected Output:

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [7]:
arr5 = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
arr5[1]

array([20, 21, 22, 23, 24])

**🌟 Exercise 6 : Reversing elements**

**Instructions**

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
arr6 = np.arange(10)[::-1]
arr6

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**🌟 Exercise 7 : Identity Matrix**

**Instructions**

Create a 4x4 identity matrix using NumPy.

Expected Output:

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr7 = np.eye(4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**🌟 Exercise 8 : Simple Aggregate Funcs**

**Instructions**

Find the sum and average of a given 1D array.

Expected Output:

Sum: 45, Average: 4.5

In [11]:
arr8 = np.arange(10)
sum_arr8 = np.sum(arr8)
avg_arr8 = np.mean(arr8)

print(f"Sum: {sum_arr8}, Average: {avg_arr8}")

Sum: 45, Average: 4.5


**🌟 Exercise 9 : Create Array and Change its Structure**

**Instructions**

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
arr9 = np.arange(1, 21).reshape(4, 5)
arr9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**🌟 Exercise 10 : Conditional Selection of Values**

**Instructions**

Extract all odd numbers from a given NumPy array.

Expected Output:

array([1, 3, 5, 7, 9])

In [13]:
arr10 = np.arange(10)
odd_numbers = arr10[arr10 % 2 ==1]
odd_numbers

array([1, 3, 5, 7, 9])